// Mascotas de demostración con imágenes reales
export const mockPets = [
  {
    id: '1',
    ownerId: '1', // admin@sabuesos.com
    name: 'Max',
    type: 'DOG',
    breed: 'Labrador Retriever',
    color: 'Dorado',
    age: 3,
    description: 'Perro muy amigable y juguetón. Le encanta nadar y jugar con pelotas. Es muy obediente y está entrenado.',
    photos: ['https://images.dog.ceo/breeds/labrador/n02099712_3503.jpg'],
    imageUrl: 'https://images.dog.ceo/breeds/labrador/n02099712_3503.jpg',
    qrCode: 'QR-MAX-001',
    microchipId: 'MX-982000123456789',
    status: 'ACTIVE',
    weight: '32 kg',
    vaccinated: true,
    lastVaccination: new Date('2024-11-15'),
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: '2',
    ownerId: '1', // admin@sabuesos.com
    name: 'Luna',
    type: 'CAT',
    breed: 'Siamés',
    color: 'Crema con puntas marrones',
    age: 2,
    description: 'Gata muy cariñosa pero tímida con extraños. Le gusta dormir en lugares altos y jugar con hilos. Tiene ojos azules hermosos.',
    photos: ['https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg'],
    imageUrl: 'https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg',
    qrCode: 'QR-LUNA-002',
    microchipId: 'MX-982000987654321',
    status: 'ACTIVE',
    weight: '4 kg',
    vaccinated: true,
    lastVaccination: new Date('2024-12-01'),
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date('2025-01-08'),
  },
  {
    id: '3',
    ownerId: '2', // usuario@sabuesos.com
    name: 'Rocky',
    type: 'DOG',
    breed: 'Beagle',
    color: 'Tricolor (blanco, negro y café)',
    age: 4,
    description: 'Perro muy activo y curioso. Le encanta explorar y seguir rastros. Es muy sociable con otros perros y personas.',
    photos: ['https://images.dog.ceo/breeds/beagle/n02088364_11136.jpg'],
    imageUrl: 'https://images.dog.ceo/breeds/beagle/n02088364_11136.jpg',
    qrCode: 'QR-ROCKY-003',
    microchipId: 'MX-982000456789123',
    status: 'ACTIVE',
    weight: '12 kg',
    vaccinated: true,
    lastVaccination: new Date('2024-10-20'),
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2025-01-09'),
  },
  {
    id: '4',
    ownerId: '2', // usuario@sabuesos.com
    name: 'Michi',
    type: 'CAT',
    breed: 'Común Europeo',
    color: 'Gris atigrado',
    age: 1,
    description: 'Gatito muy juguetón y travieso. Le encanta trepar y cazar juguetes. Es muy cariñoso y ronronea mucho.',
    photos: ['https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg'],
    imageUrl: 'https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg',
    qrCode: 'QR-MICHI-004',
    microchipId: 'MX-982000789123456',
    status: 'ACTIVE',
    weight: '3.5 kg',
    vaccinated: true,
    lastVaccination: new Date('2024-11-30'),
    createdAt: new Date('2024-09-05'),
    updatedAt: new Date('2025-01-11'),
  },
  {
    id: '5',
    ownerId: '1', // admin@sabuesos.com
    name: 'Simba',
    type: 'DOG',
    breed: 'Golden Retriever',
    color: 'Dorado claro',
    age: 5,
    description: 'Perro muy noble y paciente. Excelente con niños. Le encanta el agua y es muy protector con la familia.',
    photos: ['https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg'],
    imageUrl: 'https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg',
    qrCode: 'QR-SIMBA-005',
    microchipId: 'MX-982000321654987',
    status: 'ACTIVE',
    weight: '35 kg',
    vaccinated: true,
    lastVaccination: new Date('2024-09-10'),
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date('2025-01-05'),
  },
];
