// Reportes de demostración para San Juan de Pasto, Nariño
export const mockReports = [
  {
    id: '1',
    type: 'LOST',
    description: 'Perro Labrador dorado, muy amigable, responde al nombre de Max. Perdido cerca del Parque Nariño. Tiene una mancha blanca en el pecho.',
    location: { latitude: 1.2136, longitude: -77.2811 },
    contactInfo: { name: 'Max', phone: '+57 300 1234567', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/labrador/n02099712_3503.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-08'),
  },
  {
    id: '2',
    type: 'FOUND',
    description: 'Gato gris con collar azul encontrado en el sector de Santiago. Muy cariñoso, parece estar bien cuidado.',
    location: { latitude: 1.2180, longitude: -77.2850 },
    contactInfo: { name: 'Moka', phone: '+57 310 9876543', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-09'),
  },
  {
    id: '3',
    type: 'SIGHTING',
    description: 'Perro pequeño blanco visto cerca del Centro Comercial Unicentro. Parecía desorientado.',
    location: { latitude: 1.2050, longitude: -77.2750 },
    contactInfo: { name: 'Coco', phone: '+57 320 5551234', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/samoyed/n02111889_4016.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: '4',
    type: 'LOST',
    description: 'Gato siamés, ojos azules, muy asustadizo. Perdido en el barrio La Floresta. Responde al nombre de Luna.',
    location: { latitude: 1.2200, longitude: -77.2780 },
    contactInfo: { name: 'Luna', phone: '+57 315 4445678', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-09'),
  },
  {
    id: '5',
    type: 'FOUND',
    description: 'Perro pastor alemán con placa de identificación encontrado en el sector de Pandiaco. Muy obediente.',
    location: { latitude: 1.2100, longitude: -77.2900 },
    contactInfo: { name: 'Bruno', phone: '+57 318 7778899', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/germanshepherd/n02106662_10803.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: '6',
    type: 'LOST',
    description: 'Perro Beagle tricolor, collar rojo. Perdido cerca de la Universidad de Nariño. Responde al nombre de Rocky.',
    location: { latitude: 1.2250, longitude: -77.2820 },
    contactInfo: { name: 'Rocky', phone: '+57 312 3334455', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/beagle/n02088364_11136.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '7',
    type: 'SIGHTING',
    description: 'Gato naranja visto en el sector de Tamasagra. Parecía tener hambre.',
    location: { latitude: 1.2080, longitude: -77.2700 },
    contactInfo: { name: 'Taco', phone: '+57 316 7778888', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/9j5.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '8',
    type: 'FOUND',
    description: 'Perro Schnauzer gris encontrado en el Parque Infantil. Muy juguetón y amigable.',
    location: { latitude: 1.2160, longitude: -77.2790 },
    contactInfo: { name: 'Toby', phone: '+57 314 5556666', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/schnauzer-miniature/n02097047_2624.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '9',
    type: 'LOST',
    description: 'Perro Husky siberiano, ojos azules, collar negro. Perdido en el barrio Aranda. Muy activo y juguetón.',
    location: { latitude: 1.2190, longitude: -77.2760 },
    contactInfo: { name: 'Rayo', phone: '+57 301 2223344', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/husky/n02110185_10047.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-07'),
  },
  {
    id: '10',
    type: 'FOUND',
    description: 'Gata persa blanca encontrada cerca del Hospital Departamental. Muy tranquila, parece estar embarazada.',
    location: { latitude: 1.2180, longitude: -77.2900 },
    contactInfo: { name: 'Bella', phone: '+57 311 4445555', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/ebv.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: '11',
    type: 'LOST',
    description: 'Perro Poodle miniatura color café. Perdido en el sector de Mijitayo. Tiene corte de pelo reciente.',
    location: { latitude: 1.2070, longitude: -77.2680 },
    contactInfo: { name: 'Milo', phone: '+57 317 6667777', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/poodle-toy/n02113624_2761.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-09'),
  },
  {
    id: '12',
    type: 'SIGHTING',
    description: 'Perro Pitbull color marrón visto en el sector de Catambuco. Parecía perdido pero amigable.',
    location: { latitude: 1.2300, longitude: -77.2950 },
    contactInfo: { name: 'Marley', phone: '+57 319 8889999', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/pitbull/IMG_20190826_121528_876.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '13',
    type: 'FOUND',
    description: 'Gato negro con manchas blancas encontrado en el barrio San Vicente. Muy asustado.',
    location: { latitude: 1.2140, longitude: -77.2830 },
    contactInfo: { name: 'Snoopy', phone: '+57 302 1112222', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/MTk0ODg5NQ.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: '14',
    type: 'LOST',
    description: 'Perro Golden Retriever, pelaje dorado largo. Perdido cerca del Estadio Libertad. Responde al nombre de Simba.',
    location: { latitude: 1.2110, longitude: -77.2770 },
    contactInfo: { name: 'Simba', phone: '+57 313 3334444', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-08'),
  },
  {
    id: '15',
    type: 'SIGHTING',
    description: 'Perro Chihuahua color crema visto en el Centro Histórico. Llevaba suéter rojo.',
    location: { latitude: 1.2138, longitude: -77.2813 },
    contactInfo: { name: 'Chispa', phone: '+57 315 5556666', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/chihuahua/n02085620_3407.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '16',
    type: 'FOUND',
    description: 'Perro Cocker Spaniel color negro encontrado en el barrio Tejar. Tiene chip de identificación.',
    location: { latitude: 1.2090, longitude: -77.2840 },
    contactInfo: { name: 'Scooby', phone: '+57 318 7778888', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/spaniel-cocker/n02102318_4582.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-09'),
  },
  {
    id: '17',
    type: 'LOST',
    description: 'Gato angora blanco, ojos verdes. Perdido en el sector de Jongovito. Muy tímido con extraños.',
    location: { latitude: 1.2260, longitude: -77.2890 },
    contactInfo: { name: 'Nala', phone: '+57 310 9990000', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/a7g.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: '18',
    type: 'SIGHTING',
    description: 'Perro Dálmata visto cerca del Terminal de Transportes. Parecía estar buscando a alguien.',
    location: { latitude: 1.2050, longitude: -77.2650 },
    contactInfo: { name: 'Pluto', phone: '+57 316 1112222', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/dalmatian/cooper2.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '19',
    type: 'FOUND',
    description: 'Perro Bulldog francés color atigrado encontrado en el Parque Bolívar. Muy amigable.',
    location: { latitude: 1.2140, longitude: -77.2815 },
    contactInfo: { name: 'Café', phone: '+57 312 3334444', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/bulldog-french/n02108915_5306.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: '20',
    type: 'LOST',
    description: 'Perro Boxer color café. Perdido en el barrio Lorenzo de Aldana. Tiene cicatriz en la pata delantera.',
    location: { latitude: 1.2170, longitude: -77.2800 },
    contactInfo: { name: 'Rocco', phone: '+57 319 5556666', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/boxer/IMG_0002.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-09'),
  },
  {
    id: '21',
    type: 'SIGHTING',
    description: 'Gato carey visto en el sector de Fátima. Parecía estar herido en una pata.',
    location: { latitude: 1.2120, longitude: -77.2720 },
    contactInfo: { name: 'Maya', phone: '+57 301 7778888', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/d68.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '22',
    type: 'FOUND',
    description: 'Perro Shih Tzu color blanco y marrón encontrado en el barrio Miraflores. Muy bien cuidado.',
    location: { latitude: 1.2210, longitude: -77.2850 },
    contactInfo: { name: 'Lassie', phone: '+57 314 9990000', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/shihtzu/n02086240_4615.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: '23',
    type: 'LOST',
    description: 'Perro Rottweiler negro con manchas café. Perdido cerca del Coliseo. Muy protector pero amigable.',
    location: { latitude: 1.2095, longitude: -77.2795 },
    contactInfo: { name: 'Hachiko', phone: '+57 317 1112222', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/rottweiler/n02106550_2026.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-08'),
  },
  {
    id: '24',
    type: 'FOUND',
    description: 'Gato común europeo gris encontrado en el sector de Obonuco. Muy sociable.',
    location: { latitude: 1.2320, longitude: -77.2970 },
    contactInfo: { name: 'Roble', phone: '+57 313 3334444', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://cdn2.thecatapi.com/images/MTUyNzU5Nw.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: '25',
    type: 'LOST',
    description: 'Perro Yorkshire Terrier miniatura. Perdido en el barrio Champagnat. Lleva moño rosa en la cabeza.',
    location: { latitude: 1.2155, longitude: -77.2775 },
    contactInfo: { name: 'Tifón', phone: '+57 310 5556666', email: 'contacto@sabuesos.com' },
    imageUrl: 'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_1625.jpg',
    status: 'ACTIVE',
    createdAt: new Date('2025-01-10'),
  },
];
